### ISSUE TITLE
Implement Close method for Wasmtime instance

### ISSUE THREAD

**Issue by cohix** [suborbital/reactr#148]
Worth a TODO or issue maybe?

_Originally posted by @ospencer in https://github.com/suborbital/reactr/pull/144#discussion_r719423796_

**Comment by rnpridgeon** [comment]
Initial findings, still need to dig in a bit more to fully understand the implications of what's being said here:

https://github.com/bytecodealliance/wasmtime-go/blob/main/ffi.go

**Comment by rnpridgeon** [comment]
I think I'll try to set up some sort of test suite to verify that the gunruntime's garbage collector actually cleans these things up using pprof

**Comment by rnpridgeon** [comment]
Unfortunately pprof doesn't provide any useful information as these are allocations performed by cgo which is outside the control of golang memory managers control. 

Instead I opted to use valgrind with a super simpler test application. 

```
package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"fmt"
	"github.com/bytecodealliance/wasmtime-go"
	"runtime"
	"sync"
	"time"
)

type CData struct {
	data *C.char
}

var ops uint64

func main() {
	var wg sync.WaitGroup

	for i:=1; i <= 1000; i++ {
		wg.Add(1)

		go func() {
			defer wg.Done()
			_, err := doWebAssembly()
			check(err)
		}()

		if i % 100 == 0 {
			fmt.Println("calling gc")
			runtime.GC()
			time.Sleep(time.Second)
			fmt.Println("gc and pause done")
		}
	}

	fmt.Println("waiting for go routines to finish")
	wg.Wait()

	fmt.Println("calling gc")
	runtime.GC()
	fmt.Println("the end")
}

// takes ownership of instance then lets it run off scope
func doWebAssembly() (interface{}, error) {

	engine := wasmtime.NewEngine()
	store := wasmtime.NewStore(engine)

	module, err := wasmtime.NewModuleFromFile(engine, "wasmtime.wat")
	check(err)

	instance, err := wasmtime.NewInstance(store, module, []wasmtime.AsExtern{})
	check(err)

	externFunc := instance.GetFunc(store, "gcd")
	return externFunc.Call(store, 6, 27)
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
```

This above test creates 1,000 wasm instances inside 1000 subroutines and lets them fall out of scope then instructs the run time to perform a garbage collection.

Letting the instances fall out of scope renders them unreachable and thus eligible for garbage collection. 

Based on the leak report generated by valgrind it's possible we have leaked some memory but there are 0 cases where valgrind is absolutely certain we have. 

```
==73640== 
==73640== HEAP SUMMARY:
==73640==     in use at exit: 655,052 bytes in 5,826 blocks
==73640==   total heap usage: 1,021,192 allocs, 1,015,366 frees, 245,481,232 bytes allocated
==73640== 
==73640== LEAK SUMMARY:
==73640==    definitely lost: 0 bytes in 0 blocks
==73640==    indirectly lost: 0 bytes in 0 blocks
==73640==      possibly lost: 27,568 bytes in 111 blocks
==73640==    still reachable: 627,484 bytes in 5,715 blocks
==73640==         suppressed: 0 bytes in 0 blocks
```

I do acknowledge that "possibly leaked"  does not instill a whole lot of hope so I made an even simpler application which uses a similar pattern to wasmtime but with CString's. 
 
 ```
package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"sync/atomic"
	"time"
	"unsafe"
)

type CData struct {
	data *C.char
}

var ops uint64

func main() {
	var wg sync.WaitGroup

	for i:=1; i <= 1000; i++ {
		wg.Add(1)

		go func() {
			defer wg.Done()
			_, err := doWebAssembly()
			check(err)
		}()

		if i % 100 == 0 {
			fmt.Println("calling gc")
			runtime.GC()
			time.Sleep(time.Second)
			fmt.Println("gc and pause done")
		}
	}

	fmt.Println("waiting for go routines to finish")
	wg.Wait()

	fmt.Println("calling gc")
	runtime.GC()
	fmt.Println("the end")
}

// takes ownership of instance then lets it run off scope
func doWebAssembly() (interface{}, error) {
	cContent := &CData{
		data: C.CString("doing webassembly"),
	}

	runtime.SetFinalizer(cContent, func (cData *CData) {
		atomic.AddUint64(&ops, 1)
		fmt.Printf("cleaning up that c data # %d\n", ops)
		C.free(unsafe.Pointer(cData.data))
	})


	return nil, nil
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
``` 

This returns a smiliar report albeit with much smaller numbers which is to be expected given the amount of data being managed outside of golang's memeory manager. 

```
==73952== 
==73952== HEAP SUMMARY:
==73952==     in use at exit: 2,232 bytes in 34 blocks
==73952==   total heap usage: 1,013 allocs, 979 frees, 19,928 bytes allocated
==73952== 
==73952== LEAK SUMMARY:
==73952==    definitely lost: 0 bytes in 0 blocks
==73952==    indirectly lost: 0 bytes in 0 blocks
==73952==      possibly lost: 1,728 bytes in 6 blocks
==73952==    still reachable: 504 bytes in 28 blocks
==73952==         suppressed: 0 bytes in 0 blocks

```

As it turns out this behavior (cgo and valgrind) has been reported by the golang community before and so far as I can tell the go developers feel this is a non-issue

https://github.com/golang/go/issues/27610


It is my opinion at this point that we should trust (for now) that wasmtime is in fact being cleaned up properly by golang's garbage collector.

Longer term however I think it would be good to validate these assumptions with some benchmark testing where we evaluate memory pressure running similar workloads across the various run times we support.
